# Generated by Django 5.0.7 on 2024-07-11 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=32)),
                ("year_release", models.IntegerField(max_length=4)),
                ("genre", models.CharField(max_length=10)),
                ("scope", models.FloatField(max_length=3)),
                ("runningTime", models.FloatField(max_length=4)),
                ("content", models.TextField()),
                ("director", models.CharField(max_length=10)),
                ("actor", models.CharField(max_length=10)),
            ],
        ),
    ]
