# Generated by Django 5.0.7 on 2024-07-11 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="runningTime",
        ),
        migrations.AddField(
            model_name="review",
            name="running_time",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="review",
            name="scope",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="review",
            name="year_release",
            field=models.IntegerField(),
        ),
    ]
