# Generated by Django 5.0.7 on 2024-07-16 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=24, verbose_name="제목")),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="idea/%Y%m%d", verbose_name="이미지"
                    ),
                ),
                ("content", models.TextField(verbose_name="내용")),
                ("interest", models.CharField(max_length=50, verbose_name="관심사")),
                (
                    "devtool",
                    models.CharField(
                        choices=[
                            ("django", "Django"),
                            ("react", "React"),
                            ("spring", "Spring"),
                            ("nodejs", "Node.js"),
                            ("java", "Java"),
                            ("cpp", "C++"),
                        ],
                        max_length=20,
                        verbose_name="개발 도구",
                    ),
                ),
            ],
        ),
    ]
