# Generated by Django 5.0.7 on 2024-07-17 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("idea", "0002_alter_post_content_alter_post_devtool_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DevTool",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("kind", models.CharField(max_length=50)),
                ("content", models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name="post",
            name="devtool",
            field=models.CharField(default="django", max_length=50),
        ),
    ]
