# Generated by Django 5.0.7 on 2024-07-17 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("idea", "0003_devtool_alter_post_devtool"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devtool",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
